name: Environment Setup

on:
  workflow_call:
    inputs:
      minikube-enabled:
        description: "Whether to setup Minikube"
        required: false
        default: true
      minikube-driver:
        description: "The driver to use for Minikube"
        required: false
        default: "none"
      minikube-cpus:
        description: "The number of CPUs to use for Minikube"
        required: false
        default: 8
      minikube-memory:
        description: "The amount of memory to use for Minikube"
        required: false
        default: 16384
      minikube-start-args:
        description: "The arguments to pass to the Minikube start command"
        required: false
        default: ""
      

steps:
  - name: Setup Minikube
    uses: medyagh/setup-minikube@latest
    with:
      addons: registry, nvidia-driver-installer, nvidia-gpu-device-plugin
      cache: true
      container-runtime: containerd