name: CI - Helm Functionality
run-name: CI - Helm Functionality - ${{ github.actor }} - ${{ github.head_ref }}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/ci_helm-chart.yaml"
      - "helm/**"
      - "tests/helm/**"
      - "pyproject.toml"
      - "**.py"

jobs:
  setup:
    name: Setup Minikube
    runs-on: [self-hosted, gpu]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Docker Setup
        uses: docker/setup-buildx-action@v3

      - name: Docker Build
        uses: docker/build-push-action@v6
        with:
          context: .
          build-args: INSTALL_OPTIONAL_DEP=default
          cache-from: type=gha,mode=max
          cache-to: type=gha,mode=max
          file: docker/Dockerfile
          push: false
          tags: localhost:5000/git-act-router

      - name: Load Image
        run: |
          minikube image load localhost:5000/git-act-router

  test:
    name: Test
    needs: setup
    runs-on: [self-hosted, gpu]
    ## Setup matrix for tests - single test at a time
    ## Primary benefit here is to easily define tests using a consistent pattern
    ## with later opportunities to run in parallel if self-hosted runner hardware allows
    strategy:
      matrix:
        ## Test names - mapped to tests/helm/<test-name>
        test-name:
          - secure-minimal-example
          - two-pods-minimal-example
          - multiple-models
      fail-fast: true
      max-parallel: 1

    steps:
      ## Setup environment
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Helm Setup
        uses: azure/setup-helm@v4.3.0

      - name: Setup Python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install openai

      ## Install Helm Chart
      - name: Install Helm Chart
        run: |
          helm upgrade --install vllm ./helm -f tests/helm/${{ matrix.test-name }}/values.yaml --debug --create-namespace ${{ matrix.test-name }}

      ## Validate
      - name: Validate
        timeout-minutes: 3
        run: |
          mkdir -p output-tests/helm/${{ matrix.test-name }}
          bash tests/scripts/port-forward.sh tests/helm/${{ matrix.test-name }}/test ${{ matrix.test-name }}

      ## Test Results
      - name: Test Results
        run: |
          echo "# Test Summary - ${{ matrix.test-name }}" >> $GITHUB_STEP_SUMMARY

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Helm Setup
        uses: azure/setup-helm@v4.3.0

      - name: Lint Helm Chart
        run: |
          helm lint helm/.

  ## (Optional) Job to enforce required check for branch protection rules
  ## Check name = "ci-helm-check"
  ## Will require this workflow to pass before merging
  # ci-helm-check:
  #   runs-on: ubuntu-latest
  #   needs: [tests, lint]
  #   steps:
  #     - run: |
  #         if ${{ needs.tests.outcome }} != "success"; then
  #           echo "Tests failed"
  #           exit 1
  #         else
  #           echo "Tests passed"
  #           exit 0
  #         fi
