name: CI - Python Tests
run-name: CI - Python Tests - ${{ github.actor }} - ${{ github.ref }}

on:
  pull_request:
    branches:
      - main
    paths:
      # - ".github/workflows/ci_python-tests.yml"
      - "**.py"
      - "pyproject.toml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  python-tests:
    name: Python Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          ignore-nothing-to-cache: true

      - name: Install Dependencies
        run: uv sync --all-extras --all-groups

      - name: Run Tests
        id: tests
        run: uv run pytest
